fix: Clean up .old files automatically

diff --git a/build-initramfs b/build-initramfs
--- a/build-initramfs
+++ b/build-initramfs
@@ -14,3 +14,6 @@ if [ -f "/boot/vmlinuz-$KERNEL_VERSION" ]; then
   cp -f "/boot/vmlinuz-$KERNEL_VERSION" "/usr/lib/modules/$KERNEL_VERSION/vmlinuz"
   echo "vmlinuz moved successfully"
 fi
+
+# Clean up .old files
+rm -f /*.old || true
